/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ElderDashboardRouteImport } from './routes/elder.dashboard'
import { Route as ElderAuthRouteImport } from './routes/elder.auth'
import { Route as ChildRegisterRouteImport } from './routes/child.register'
import { Route as ChildDashboardRouteImport } from './routes/child.dashboard'
import { Route as ChildAuthRouteImport } from './routes/child.auth'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElderDashboardRoute = ElderDashboardRouteImport.update({
  id: '/elder/dashboard',
  path: '/elder/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ElderAuthRoute = ElderAuthRouteImport.update({
  id: '/elder/auth',
  path: '/elder/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildRegisterRoute = ChildRegisterRouteImport.update({
  id: '/child/register',
  path: '/child/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildDashboardRoute = ChildDashboardRouteImport.update({
  id: '/child/dashboard',
  path: '/child/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildAuthRoute = ChildAuthRouteImport.update({
  id: '/child/auth',
  path: '/child/auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/child/auth': typeof ChildAuthRoute
  '/child/dashboard': typeof ChildDashboardRoute
  '/child/register': typeof ChildRegisterRoute
  '/elder/auth': typeof ElderAuthRoute
  '/elder/dashboard': typeof ElderDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/child/auth': typeof ChildAuthRoute
  '/child/dashboard': typeof ChildDashboardRoute
  '/child/register': typeof ChildRegisterRoute
  '/elder/auth': typeof ElderAuthRoute
  '/elder/dashboard': typeof ElderDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/child/auth': typeof ChildAuthRoute
  '/child/dashboard': typeof ChildDashboardRoute
  '/child/register': typeof ChildRegisterRoute
  '/elder/auth': typeof ElderAuthRoute
  '/elder/dashboard': typeof ElderDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/child/auth'
    | '/child/dashboard'
    | '/child/register'
    | '/elder/auth'
    | '/elder/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/child/auth'
    | '/child/dashboard'
    | '/child/register'
    | '/elder/auth'
    | '/elder/dashboard'
  id:
    | '__root__'
    | '/'
    | '/child/auth'
    | '/child/dashboard'
    | '/child/register'
    | '/elder/auth'
    | '/elder/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChildAuthRoute: typeof ChildAuthRoute
  ChildDashboardRoute: typeof ChildDashboardRoute
  ChildRegisterRoute: typeof ChildRegisterRoute
  ElderAuthRoute: typeof ElderAuthRoute
  ElderDashboardRoute: typeof ElderDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elder/dashboard': {
      id: '/elder/dashboard'
      path: '/elder/dashboard'
      fullPath: '/elder/dashboard'
      preLoaderRoute: typeof ElderDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elder/auth': {
      id: '/elder/auth'
      path: '/elder/auth'
      fullPath: '/elder/auth'
      preLoaderRoute: typeof ElderAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child/register': {
      id: '/child/register'
      path: '/child/register'
      fullPath: '/child/register'
      preLoaderRoute: typeof ChildRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child/dashboard': {
      id: '/child/dashboard'
      path: '/child/dashboard'
      fullPath: '/child/dashboard'
      preLoaderRoute: typeof ChildDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child/auth': {
      id: '/child/auth'
      path: '/child/auth'
      fullPath: '/child/auth'
      preLoaderRoute: typeof ChildAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChildAuthRoute: ChildAuthRoute,
  ChildDashboardRoute: ChildDashboardRoute,
  ChildRegisterRoute: ChildRegisterRoute,
  ElderAuthRoute: ElderAuthRoute,
  ElderDashboardRoute: ElderDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
